version: '3.7'
services:
  tiny:
    image: "cr.yandex/crp8j4r52de87520rrk6/bf:v3"
    command:
      - 'find-all-outputs-debug'
      - '--node-count'
      - '4'
      - '--bits'
      - '6'
      - '--config'
      - '(output=[beta:()])'
    restart: none
  app5s:
    image: "cr.yandex/crp8j4r52de87520rrk6/bf:v3"
    command:
      - 'find-all-outputs-release'
      - '--node-count'
      - '5'
      - '--bits'
      - '8'
      - '--config'
      - '(filter=(unsafe=true),output=[beta:()])'
    restart: none
  app5l:
    image: "cr.yandex/crp8j4r52de87520rrk6/bf:v3"
    command:
      - 'find-all-outputs-release'
      - '--node-count'
      - '5'
      - '--bits'
      - '10'
      - '--config'
      - '(filter=(unsafe=true),output=[beta:()])'
    restart: none
  app6s:
    image: "cr.yandex/crp8j4r52de87520rrk6/bf:v3"
    command:
      - 'find-all-outputs-release'
      - '--node-count'
      - '6'
      - '--bits'
      - '8'
      - '--config'
      - '(filter=(unsafe=true),output=[beta:()])'
    restart: none
  app6l:
    image: "cr.yandex/crp8j4r52de87520rrk6/bf:v3"
    command:
      - 'find-all-outputs-release'
      - '--node-count'
      - '6'
      - '--bits'
      - '10'
      - '--config'
      - '(filter=(unsafe=true),output=[beta:()])'
    restart: none
