version: '3.7'
services:
  app6s:
    image: "cr.yandex/crp8j4r52de87520rrk6/bf:${version}"
    command:
      - 'find-all-outputs-release'
      - '--node-count'
      - '6'
      - '--config'
      - '(eval=(engine=[beta:(print_topology=(enabled=true,x=251,y=5))],settings=(max_bits=8,second_output=[enabled:(x=181,y=-181)])),launch=(parallel=true))'
      - '--output-path'
      - '/out/6s'
    restart: none
    volumes:
      - outputs:/out
  app6l:
    image: "cr.yandex/crp8j4r52de87520rrk6/bf:${version}"
    command:
      - 'find-all-outputs-release'
      - '--node-count'
      - '6'
      - '--config'
      - '(eval=(engine=[beta:(print_topology=(enabled=true,x=251,y=5))],settings=(max_bits=9,second_output=[enabled:(x=181,y=-181)])),launch=(parallel=true))'
      - '--output-path'
      - '/out/6l'
    restart: none
    volumes:
      - outputs:/out
volumes:
  outputs: {}