version: '3.7'
services:
  tiny:
    image: "cr.yandex/crp8j4r52de87520rrk6/bf:${version}"
    command:
      - 'find-all-outputs-debug'
      - '--node-count'
      - '4'
      - '--bits'
      - '6'
      - '--config'
      - '(eval=[beta:()],launch=(parallel=true))'
      - '--output-path'
      - '/out/tiny'
    restart: none
    volumes:
      - outputs:/out
  app5s:
    image: "cr.yandex/crp8j4r52de87520rrk6/bf:${version}"
    command:
      - 'find-all-outputs-release'
      - '--node-count'
      - '5'
      - '--bits'
      - '7'
      - '--config'
      - '(eval=[beta:()],launch=(parallel=true))'
      - '--output-path'
      - '/out/5s'
    restart: none
    volumes:
      - outputs:/out
  app5l:
    image: "cr.yandex/crp8j4r52de87520rrk6/bf:${version}"
    command:
      - 'find-all-outputs-release'
      - '--node-count'
      - '5'
      - '--bits'
      - '9'
      - '--config'
      - '(eval=[beta:()],launch=(parallel=true))'
      - '--output-path'
      - '/out/5l'
    restart: none
    volumes:
      - outputs:/out
  app6s:
    image: "cr.yandex/crp8j4r52de87520rrk6/bf:${version}"
    command:
      - 'find-all-outputs-release'
      - '--node-count'
      - '6'
      - '--bits'
      - '7'
      - '--config'
      - '(eval=[beta:()],launch=(parallel=true))'
      - '--output-path'
      - '/out/6s'
    restart: none
    volumes:
      - outputs:/out
  app6l:
    image: "cr.yandex/crp8j4r52de87520rrk6/bf:${version}"
    command:
      - 'find-all-outputs-release'
      - '--node-count'
      - '6'
      - '--bits'
      - '9'
      - '--config'
      - '(eval=[beta:()],launch=(parallel=true))'
      - '--output-path'
      - '/out/6l'
    restart: none
    volumes:
      - outputs:/out
volumes:
  outputs: {}